#GUI部分设置
gui:
  #无关紧要
  1:
    #位置，如果是某一个位置，填写数字，多个请按照｛格子-格子｝的格式来写
    slot: 0-11
    #从SCT_Core的items.yml内读取
    item: fenge
  2:
    slot: 12-15
    item: fenge
  3:
    slot: 16-31
    item: fenge
  4:
    slot: 32-45
    item: fenge

#这是一个辅助选项，你将需要放入被修复物品的那个格子位置和修复道具的物品格子位置填进去，用|分割
BlankSlot: 10|12

#修复石所需要的物品，从SCT_Core内读取
repair: repair
#镶嵌无法破坏Lore所需的物品，从SCT_Core内读取
unbreak: buxiu
#这是镶嵌后所添加的Lore
unbreaklore: "&c无法破坏"